// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAnA66FZFpcRHjVYQBUgsSSKNt1W2x92MM',
    appId: '1:943413367295:android:dcc28cbafee40e5d1f17ca',
    messagingSenderId: '943413367295',
    projectId: 'cuidapet-linykeer',
    storageBucket: 'cuidapet-linykeer.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCG2chLyeUFBKs0Jj4p0KaWZ2KGFCMWMhM',
    appId: '1:943413367295:ios:91926911048de1ad1f17ca',
    messagingSenderId: '943413367295',
    projectId: 'cuidapet-linykeer',
    storageBucket: 'cuidapet-linykeer.appspot.com',
    androidClientId: '943413367295-rsacscnqt0to58md4l7brqb4mfo7pruq.apps.googleusercontent.com',
    iosClientId: '943413367295-0u2nvmop61qv1r0h4r2e15emka34dsno.apps.googleusercontent.com',
    iosBundleId: 'lasistem.com.br.cuidapet.cuidapet',
  );
}
